import { useState } from 'react'
import { Link, Navigate, Route, Routes, useLocation, useNavigate } from 'react-router-dom'
import {
  Activity,
  ArrowRight,
  BarChart3,
  Bell,
  BookOpen,
  Check,
  ChevronDown,
  Clock3,
  Code2,
  FileText,
  Filter,
  FolderKanban,
  Gauge,
  GraduationCap,
  LayoutDashboard,
  Menu,
  MoreHorizontal,
  Plus,
  Search,
  Settings,
  ShieldAlert,
  SlidersHorizontal,
  Sparkles,
  Target,
  Users,
  X,
} from 'lucide-react'

type TestCase = { name: string; category: string; marks: number; visibility: 'Public' | 'Hidden'; enabled: boolean }

const navItems = [
  { label: 'Overview', path: '/teacher/dashboard', icon: LayoutDashboard },
  { label: 'Assessments', path: '/teacher/assessments', icon: BookOpen },
  { label: 'Submissions', path: '/teacher/submissions', icon: FileText, count: 12 },
  { label: 'Students', path: '/teacher/students', icon: Users },
  { label: 'Integrity review', path: '/teacher/integrity', icon: ShieldAlert, count: 3 },
]

const tests: TestCase[] = [
  { name: 'Basic positive numbers', category: 'Basic', marks: 5, visibility: 'Public', enabled: true },
  { name: 'Single element input', category: 'Edge Case', marks: 5, visibility: 'Public', enabled: true },
  { name: 'Zero and negatives', category: 'Negative', marks: 10, visibility: 'Hidden', enabled: true },
  { name: 'Maximum constraints', category: 'Stress', marks: 10, visibility: 'Hidden', enabled: true },
]

function App() {
  return <Routes><Route path="*" element={<AppShell />} /></Routes>
}

function AppShell() {
  const location = useLocation()
  const navigate = useNavigate()
  const [sidebarOpen, setSidebarOpen] = useState(false)
  const activePath = location.pathname === '/' ? '/teacher/dashboard' : location.pathname
  const isBuilder = location.pathname.includes('/assessments/new')

  if (location.pathname === '/') return <Navigate to="/teacher/dashboard" replace />

  return (
    <div className="app-shell">
      <aside className={`sidebar ${sidebarOpen ? 'is-open' : ''}`}>
        <div className="brand"><div className="brand-mark">V</div><div><strong>vayavya</strong><span>learning systems</span></div></div>
        <div className="workspace-switcher"><div className="avatar avatar-amber">SP</div><div><b>Sarah Patel</b><span>Teacher workspace</span></div><ChevronDown size={15} /></div>
        <div className="nav-label">Workspace</div>
        <nav>{navItems.map(({ label, path, icon: Icon, count }) => <Link key={path} to={path} onClick={() => setSidebarOpen(false)} className={`nav-item ${activePath === path ? 'active' : ''}`}><Icon size={18} /><span>{label}</span>{count && <em>{count}</em>}</Link>)}</nav>
        <div className="nav-label nav-label-spaced">Manage</div>
        <nav><Link to="/teacher/analytics" className={`nav-item ${activePath === '/teacher/analytics' ? 'active' : ''}`}><BarChart3 size={18} /><span>Analytics</span></Link><Link to="/teacher/settings" className="nav-item"><Settings size={18} /><span>Settings</span></Link></nav>
        <div className="sidebar-footer"><div className="status-dot" /><div><b>All systems operational</b><span>Last synced just now</span></div></div>
      </aside>
      <main className="main-content">
        <header className="topbar"><button className="icon-button mobile-menu" onClick={() => setSidebarOpen(!sidebarOpen)} aria-label="Open navigation"><Menu size={20} /></button><div className="breadcrumbs"><span>Teacher workspace</span><ArrowRight size={13} /><b>{isBuilder ? 'New assessment' : location.pathname.includes('assessments') ? 'Assessments' : 'Overview'}</b></div><div className="topbar-actions"><button className="icon-button" aria-label="Search"><Search size={19} /></button><button className="icon-button notification" aria-label="Notifications"><Bell size={19} /><i /></button><div className="top-avatar">SP</div></div></header>
        <Routes>
          <Route path="/teacher/dashboard" element={<Dashboard />} />
          <Route path="/teacher/assessments" element={<Assessments />} />
          <Route path="/teacher/assessments/new" element={<AssessmentBuilder />} />
          <Route path="/teacher/submissions" element={<Submissions />} />
          <Route path="/teacher/integrity" element={<Integrity />} />
          <Route path="/teacher/students" element={<Students />} />
          <Route path="/teacher/settings" element={<SettingsPage />} />
          <Route path="*" element={<Dashboard />} />
        </Routes>
      </main>
    </div>
  )
}

function PageHeader({ eyebrow, title, description, action }: { eyebrow?: string; title: string; description?: string; action?: React.ReactNode }) { return <div className="page-header"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1>{description && <p>{description}</p>}</div>{action}</div> }

function Dashboard() {
  const navigate = useNavigate()
  return <div className="page"><PageHeader eyebrow="Tuesday, 22 September 2026" title="Good morning, Sarah" description="Here’s what’s happening across your learning spaces." action={<button className="button button-primary" onClick={() => navigate('/teacher/assessments/new')}><Plus size={17} /> New assessment</button>} />
    <section className="stat-grid"><StatCard label="Total assessments" value="24" note="+3 this month" icon={FolderKanban} tone="coral" /><StatCard label="Active students" value="186" note="+12% vs last term" icon={Users} tone="teal" /><StatCard label="Pending submissions" value="32" note="8 due today" icon={Clock3} tone="gold" /><StatCard label="Average score" value="78.4%" note="+4.8% this month" icon={Target} tone="blue" /></section>
    <div className="dashboard-grid"><section className="panel activity-panel"><div className="panel-heading"><div><h2>Submission activity</h2><span>Last 30 days</span></div><button className="select-button">Last 30 days <ChevronDown size={14} /></button></div><div className="chart-wrap"><div className="chart-y"><span>40</span><span>30</span><span>20</span><span>10</span><span>0</span></div><div className="chart"><div className="grid-lines"><i /><i /><i /><i /><i /></div><svg viewBox="0 0 720 220" preserveAspectRatio="none" aria-label="Submission activity chart"><path className="chart-area" d="M0 182 C45 175 55 145 95 155 S155 122 190 138 S238 104 280 118 S325 70 368 90 S408 56 452 74 S495 80 530 46 S575 62 612 36 S675 60 720 20 V220 H0 Z" /><path className="chart-line" d="M0 182 C45 175 55 145 95 155 S155 122 190 138 S238 104 280 118 S325 70 368 90 S408 56 452 74 S495 80 530 46 S575 62 612 36 S675 60 720 20" /></svg><div className="chart-x"><span>Aug 24</span><span>Aug 31</span><span>Sep 7</span><span>Sep 14</span><span>Sep 22</span></div></div></div></section><section className="panel review-panel"><div className="panel-heading"><div><h2>Needs your attention</h2><span>Prioritized for review</span></div><Link to="/teacher/submissions" className="text-link">View all <ArrowRight size={14} /></Link></div><div className="review-list"><ReviewItem icon={ShieldAlert} tone="coral" title="Integrity review" detail="Aarav Mehta · C fundamentals" time="8 min ago" /><ReviewItem icon={FileText} tone="gold" title="Submission to grade" detail="Binary trees · 4 students" time="26 min ago" /><ReviewItem icon={Activity} tone="teal" title="Assessment closes soon" detail="Pointers & memory · 14 students" time="Tomorrow" /></div></section></div>
    <section className="panel table-panel"><div className="panel-heading"><div><h2>Recent assessments</h2><span>Latest activity from your workspace</span></div><Link to="/teacher/assessments" className="text-link">All assessments <ArrowRight size={14} /></Link></div><AssessmentTable compact /></section>
  </div>
}

function StatCard({ label, value, note, icon: Icon, tone }: { label: string; value: string; note: string; icon: typeof Gauge; tone: string }) { return <div className={`stat-card ${tone}`}><div className="stat-top"><span>{label}</span><div className="stat-icon"><Icon size={18} /></div></div><strong>{value}</strong><small><span className="trend">↗</span> {note}</small></div> }
function ReviewItem({ icon: Icon, tone, title, detail, time }: { icon: typeof ShieldAlert; tone: string; title: string; detail: string; time: string }) { return <div className="review-item"><div className={`review-icon ${tone}`}><Icon size={17} /></div><div><b>{title}</b><span>{detail}</span></div><time>{time}</time></div> }

function Assessments() { const navigate = useNavigate(); return <div className="page"><PageHeader eyebrow="Workspace" title="Assessments" description="Create, manage, and monitor your learning assessments." action={<button className="button button-primary" onClick={() => navigate('/teacher/assessments/new')}><Plus size={17} /> New assessment</button>} /><div className="toolbar"><div className="search-field"><Search size={17} /><input placeholder="Search assessments" /></div><button className="filter-button"><Filter size={16} /> Filters <span>2</span></button><button className="view-toggle"><span className="active"><FolderKanban size={16} /></span><span><FileText size={16} /></span></button></div><section className="panel table-panel"><AssessmentTable /></section></div> }

function AssessmentTable({ compact = false }: { compact?: boolean }) { const rows = [{ title: 'C Fundamentals: Arrays & Pointers', type: 'C TEST', status: 'Active', submissions: '18 / 32', score: '81.2%', date: 'Sep 26, 2026' }, { title: 'Systems Thinking — Reflection', type: 'GENERAL', status: 'Active', submissions: '27 / 32', score: '76.8%', date: 'Sep 24, 2026' }, { title: 'Introduction to Algorithms', type: 'C TEST', status: 'Draft', submissions: '—', score: '—', date: 'Oct 02, 2026' }, { title: 'Debugging Journal: Week 3', type: 'GENERAL', status: 'Closed', submissions: '31 / 31', score: '84.1%', date: 'Sep 18, 2026' }]; return <table><thead><tr><th>Assessment</th><th>Status</th><th>Submissions</th><th>Avg. score</th><th>Due date</th><th /></tr></thead><tbody>{rows.slice(0, compact ? 3 : 4).map(row => <tr key={row.title}><td><div className="assessment-cell"><div className={`type-badge ${row.type === 'C TEST' ? 'c-type' : 'general-type'}`}>{row.type === 'C TEST' ? '<>' : 'Aa'}</div><div><b>{row.title}</b><span>{row.type === 'C TEST' ? 'Programming assessment' : 'File submission'}</span></div></div></td><td><span className={`status ${row.status.toLowerCase()}`}><i />{row.status}</span></td><td>{row.submissions}</td><td><b>{row.score}</b></td><td>{row.date}</td><td><button className="icon-button"><MoreHorizontal size={18} /></button></td></tr>)}</tbody></table> }

function AssessmentBuilder() { const [activeTab, setActiveTab] = useState('Basics'); const [cases, setCases] = useState(tests); const [saved, setSaved] = useState(false); const tabs = ['Basics', 'Questions', 'Test cases', 'Rubric', 'Review']; return <div className="page builder-page"><PageHeader eyebrow="New assessment" title="Build an assessment" description="Set up the brief, evaluation rules, and student experience." action={<><button className="button button-quiet" onClick={() => window.history.back()}>Discard</button><button className="button button-primary" onClick={() => setSaved(true)}>{saved ? <><Check size={16} /> Saved</> : 'Save draft'}</button></>} /><div className="builder-tabs">{tabs.map(tab => <button key={tab} onClick={() => setActiveTab(tab)} className={activeTab === tab ? 'active' : ''}><span>{tabs.indexOf(tab) + 1}</span>{tab}</button>)}</div>{activeTab === 'Basics' && <Basics onContinue={() => setActiveTab('Questions')} />}{activeTab === 'Questions' && <QuestionEditor onContinue={() => setActiveTab('Test cases')} />}{activeTab === 'Test cases' && <TestCaseManager cases={cases} setCases={setCases} />}{activeTab === 'Rubric' && <Rubric />}{activeTab === 'Review' && <Review assessmentSaved={saved} />}</div> }
function Basics({ onContinue }: { onContinue: () => void }) { return <div className="builder-layout"><section className="panel form-panel"><div className="panel-heading"><div><h2>Assessment details</h2><span>Start with the essentials</span></div></div><div className="form-grid"><label className="full">Title<input defaultValue="C Fundamentals: Arrays & Pointers" /></label><label className="full">Description<textarea defaultValue="Assess practical understanding of arrays, pointers, and memory management in C." /></label><label>Assessment type<select defaultValue="C_TEST"><option value="C_TEST">C Test</option><option>General submission</option></select></label><label>Maximum marks<input type="number" defaultValue="100" /></label><label>Start date<input type="date" defaultValue="2026-09-22" /></label><label>End date<input type="date" defaultValue="2026-09-26" /></label><label>Duration<select defaultValue="60"><option value="60">60 minutes</option><option>90 minutes</option><option>120 minutes</option></select></label><label>Attempt limit<input type="number" defaultValue="2" /></label></div><div className="form-footer"><span><Sparkles size={15} /> Draft changes are saved locally</span><button className="button button-primary" onClick={onContinue}>Continue to questions <ArrowRight size={16} /></button></div></section><aside className="builder-aside"><div className="side-note"><div className="note-icon"><Target size={18} /></div><h3>Design for learning</h3><p>Clear instructions and a focused rubric help students spend their energy on demonstrating understanding.</p></div><div className="side-summary"><span>Assessment status</span><strong>Draft</strong><small>Only visible to you until published.</small></div></aside></div> }
function QuestionEditor({ onContinue }: { onContinue: () => void }) { return <section className="panel form-panel"><div className="panel-heading"><div><h2>Questions</h2><span>Build the problems students will solve</span></div><button className="button button-secondary"><Plus size={16} /> Add question</button></div><div className="question-card"><div className="question-number">01</div><div className="question-content"><div className="question-title-row"><div><span className="eyebrow">C · Medium · 40 marks</span><h3>Find the second largest element</h3></div><button className="icon-button"><MoreHorizontal size={18} /></button></div><p>Write a program that finds the second largest distinct integer in an array without sorting the input.</p><div className="question-meta"><span><Code2 size={15} /> C</span><span><Clock3 size={15} /> 1 sec</span><span><Gauge size={15} /> 128 MB</span><span>4 test cases</span></div></div></div><button className="continue-button" onClick={onContinue}>Manage test cases <ArrowRight size={16} /></button></section> }
function TestCaseManager({ cases, setCases }: { cases: TestCase[]; setCases: React.Dispatch<React.SetStateAction<TestCase[]>> }) { const [editing, setEditing] = useState<number | null>(null); const addCase = () => setCases([...cases, { name: 'New test case', category: 'Custom', marks: 5, visibility: 'Hidden', enabled: true }]); return <section className="panel test-manager"><div className="panel-heading"><div><h2>Test cases</h2><span>Second largest element · 4 cases configured</span></div><button className="button button-primary" onClick={addCase}><Plus size={16} /> Add test case</button></div><div className="test-summary"><div><b>{cases.length}</b><span>Total tests</span></div><div><b>{cases.filter(test => test.visibility === 'Public').length}</b><span>Public tests</span></div><div><b>{cases.filter(test => test.visibility === 'Hidden').length}</b><span>Hidden tests</span></div><div><b>{cases.reduce((sum, test) => sum + test.marks, 0)}</b><span>Total test marks</span></div></div><div className="test-list">{cases.map((test, index) => <div className={`test-row ${!test.enabled ? 'disabled' : ''}`} key={`${test.name}-${index}`}><button className="drag-handle" aria-label="Reorder test case">⠿</button><div className="test-order">{String(index + 1).padStart(2, '0')}</div><div className="test-details"><b>{test.name}</b><span>{test.category} · {test.marks} marks</span></div><span className={`visibility ${test.visibility.toLowerCase()}`}>{test.visibility}</span><button className={`switch ${test.enabled ? 'on' : ''}`} onClick={() => setCases(cases.map((item, itemIndex) => itemIndex === index ? { ...item, enabled: !item.enabled } : item))} aria-label="Toggle test case"><i /></button><button className="edit-link" onClick={() => setEditing(editing === index ? null : index)}>{editing === index ? 'Close' : 'Edit'}</button><button className="icon-button" onClick={() => setCases(cases.filter((_, itemIndex) => itemIndex !== index))} aria-label="Delete test case"><X size={16} /></button>{editing === index && <div className="inline-edit"><label>Test name<input value={test.name} onChange={event => setCases(cases.map((item, itemIndex) => itemIndex === index ? { ...item, name: event.target.value } : item))} /></label><label>Category<select value={test.category} onChange={event => setCases(cases.map((item, itemIndex) => itemIndex === index ? { ...item, category: event.target.value } : item))}><option>Basic</option><option>Edge Case</option><option>Boundary</option><option>Negative</option><option>Stress</option><option>Custom</option></select></label><label>Marks<input type="number" value={test.marks} onChange={event => setCases(cases.map((item, itemIndex) => itemIndex === index ? { ...item, marks: Number(event.target.value) } : item))} /></label></div>}</div>)}</div></section> }
function Rubric() { const [criteria, setCriteria] = useState([{ name: 'Compilation', marks: 10 }, { name: 'Correctness', marks: 30 }, { name: 'Algorithm', marks: 20 }, { name: 'Edge cases', marks: 15 }, { name: 'Code quality', marks: 15 }, { name: 'Documentation', marks: 10 }]); return <section className="panel rubric-panel"><div className="panel-heading"><div><h2>Evaluation rubric</h2><span>Configure how this assessment is scored</span></div><button className="button button-secondary" onClick={() => setCriteria([...criteria, { name: 'New criterion', marks: 0 }])}><Plus size={16} /> Add criterion</button></div><div className="rubric-total"><div><span>Total marks</span><strong>{criteria.reduce((sum, item) => sum + item.marks, 0)} <small>/ 100</small></strong></div><div className="progress"><i style={{ width: `${Math.min(criteria.reduce((sum, item) => sum + item.marks, 0), 100)}%` }} /></div></div><div className="criteria-list">{criteria.map((criterion, index) => <div className="criterion" key={`${criterion.name}-${index}`}><span className="criterion-order">{index + 1}</span><input value={criterion.name} onChange={event => setCriteria(criteria.map((item, itemIndex) => itemIndex === index ? { ...item, name: event.target.value } : item))} /><input className="marks-input" type="number" value={criterion.marks} onChange={event => setCriteria(criteria.map((item, itemIndex) => itemIndex === index ? { ...item, marks: Number(event.target.value) } : item))} /><span>marks</span><button className="icon-button" onClick={() => setCriteria(criteria.filter((_, itemIndex) => itemIndex !== index))}><X size={16} /></button></div>)}</div></section> }
function Review({ assessmentSaved }: { assessmentSaved: boolean }) { return <section className="review-screen"><div className="review-hero"><div className="success-mark"><Check size={22} /></div><div><h2>Ready to review</h2><p>Your assessment has {assessmentSaved ? 'been saved as a draft' : 'the essentials in place'}. Check the details before publishing.</p></div></div><div className="review-checklist"><div><Check size={16} /> Assessment details complete</div><div><Check size={16} /> 1 question configured</div><div><Check size={16} /> 4 test cases added</div><div><Check size={16} /> Rubric totals 100 marks</div></div><button className="button button-primary">Publish assessment <ArrowRight size={16} /></button></section> }

function Submissions() { return <div className="page"><PageHeader eyebrow="Workspace" title="Submissions" description="Review work, apply rubric scores, and keep feedback moving." /><div className="toolbar"><div className="search-field"><Search size={17} /><input placeholder="Search students or assessments" /></div><button className="filter-button"><SlidersHorizontal size={16} /> All statuses <ChevronDown size={15} /></button></div><section className="panel table-panel"><table><thead><tr><th>Student</th><th>Assessment</th><th>Submitted</th><th>Score</th><th>Integrity</th><th>Status</th><th /></tr></thead><tbody>{[['Aarav Mehta','C Fundamentals: Arrays & Pointers','Today, 10:42','—','Review','Pending'],['Maya Chen','Systems Thinking — Reflection','Today, 09:18','92%','Clear','Graded'],['Noah Williams','C Fundamentals: Arrays & Pointers','Yesterday, 16:04','78%','Clear','Graded'],['Lina Gomez','Debugging Journal: Week 3','Yesterday, 14:31','—','Clear','Pending']].map(row => <tr key={row[0] + row[1]}><td><div className="student-cell"><div className="avatar avatar-coral">{row[0].split(' ').map(name => name[0]).join('')}</div><b>{row[0]}</b></div></td><td>{row[1]}</td><td>{row[2]}</td><td><b>{row[3]}</b></td><td><span className={`status ${row[4].toLowerCase()}`}><i />{row[4]}</span></td><td><span className={`status ${row[5].toLowerCase()}`}><i />{row[5]}</span></td><td><button className="icon-button"><MoreHorizontal size={18} /></button></td></tr>)}</tbody></table></section></div> }
function Integrity() { return <div className="page"><PageHeader eyebrow="Academic integrity" title="Integrity review" description="Evidence-led signals to support fair, human conversations about student work." /><div className="integrity-callout"><ShieldAlert size={19} /><div><b>Signals are not proof of AI use</b><span>Review activity, code evolution, and student context together. This workspace never presents an AI score as a definitive detector.</span></div></div><section className="stat-grid"><StatCard label="Needs review" value="3" note="2 new today" icon={ShieldAlert} tone="coral" /><StatCard label="Reviewed this week" value="18" note="6% of submissions" icon={Check} tone="teal" /><StatCard label="Clear signals" value="91%" note="Across all submissions" icon={Gauge} tone="blue" /><StatCard label="Similarity clusters" value="2" note="Requires context" icon={Activity} tone="gold" /></section><section className="panel table-panel"><div className="panel-heading"><div><h2>Review queue</h2><span>Sorted by most recent signal</span></div><button className="filter-button"><Filter size={16} /> Filter</button></div><table><thead><tr><th>Student</th><th>Assessment</th><th>Indicators</th><th>Confidence</th><th>Submitted</th><th /></tr></thead><tbody>{[['Aarav Mehta','C Fundamentals: Arrays & Pointers','Large code insertion · Low incremental development','Medium','8 min ago'],['Priya Shah','Introduction to Algorithms','Similarity with another submission','Low','Yesterday'],['Ethan Brown','C Fundamentals: Arrays & Pointers','Strong incremental development','Low','Sep 20']].map(row => <tr key={row[0]}><td><b>{row[0]}</b></td><td>{row[1]}</td><td><span className="indicator-text"><i />{row[2]}</span></td><td><span className={`confidence ${row[3].toLowerCase()}`}>{row[3]}</span></td><td>{row[4]}</td><td><button className="button button-small">Review <ArrowRight size={14} /></button></td></tr>)}</tbody></table></section></div> }
function Students() { return <div className="page"><PageHeader eyebrow="Workspace" title="Students" description="Track participation and progress across your learning spaces." action={<button className="button button-primary"><Plus size={17} /> Invite students</button>} /><section className="panel table-panel"><div className="toolbar embedded"><div className="search-field"><Search size={17} /><input placeholder="Search students" /></div><button className="filter-button"><Filter size={16} /> Cohort <ChevronDown size={15} /></button></div><table><thead><tr><th>Student</th><th>Assessments</th><th>Avg. score</th><th>Last active</th><th>Status</th><th /></tr></thead><tbody>{[['Maya Chen','12 / 14','92%','Today','Active'],['Aarav Mehta','11 / 14','84%','Today','Active'],['Noah Williams','14 / 14','78%','Yesterday','Active'],['Lina Gomez','9 / 14','71%','Sep 18','Needs attention']].map(row => <tr key={row[0]}><td><div className="student-cell"><div className="avatar avatar-teal">{row[0].split(' ').map(name => name[0]).join('')}</div><b>{row[0]}</b></div></td><td>{row[1]}</td><td><b>{row[2]}</b></td><td>{row[3]}</td><td><span className={`status ${row[4] === 'Active' ? 'active' : 'pending'}`}><i />{row[4]}</span></td><td><button className="icon-button"><MoreHorizontal size={18} /></button></td></tr>)}</tbody></table></section></div> }
function SettingsPage() { return <div className="page"><PageHeader eyebrow="Workspace" title="Settings" description="Manage your profile and assessment defaults." /><section className="panel form-panel settings-panel"><div className="panel-heading"><div><h2>Profile</h2><span>Shown to students in feedback and course spaces</span></div></div><div className="profile-settings"><div className="large-avatar">SP</div><div><h3>Sarah Patel</h3><p>sarah.patel@vayavya.training</p><button className="button button-secondary">Change photo</button></div></div><div className="form-grid"><label>Display name<input defaultValue="Sarah Patel" /></label><label>Role<input defaultValue="Teacher" disabled /></label><label className="full">Workspace name<input defaultValue="Vayavya Training" /></label></div><div className="form-footer"><span>Changes are saved to your profile</span><button className="button button-primary">Save changes</button></div></section></div> }

export default App
